general {
    ignore_dbus_inhibit = false
}

listener {
    timeout    = 240
    on-timeout = uwsm-app -- quickshell -p ~/.config/quickshell/idle-overlay
}

listener {
    timeout    = 300
    on-timeout = uwsm-app -- quickshell -p ~/.config/quickshell/lockscreen
}

listener {
    timeout    = 900
    on-timeout = systemctl suspend
}

listener {
    timeout = 230
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 230
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}
